.PHONY: all
all: format lint test type_check

.PHONY: format
format:
	ruff format .

.PHONY: lint
lint:
	ruff check --fix .
	bash commit_lint.sh

.PHONY: test
test:
	pytest tests/

.PHONY: type_check
type_check:
	pyright ticketing_service/

.PHONY: clean
clean:
	rm -rf .pytest_cache .tox dist .coverage ambulance.egg-info build celerybeat-schedule .ruff_cache .testmondata
	py3clean .

.PHONY: changelog
changelog:
	git-changelog --style conventional \
		--sections feat,fix,chore,revert,refactor,perf,build,ci,deps,docs,style,test \
		--template keepachangelog \
		--bump=auto \
		-o CHANGELOG.md

.PHONY: package
package:
	tox -e package

.PHONY: publish
publish:
	tox -e publish

.PHONY: help
help:
	@echo "Usage:"
	@echo "  make"
	@echo "  	Run ruff, pyright & pytest"
	@echo "  make test"
	@echo "  	Run pytest & output coverage results"
	@echo "  make test_incr"
	@echo "  	Run only tests with recent changes (speedup!)"
	@echo "  make lint"
	@echo "  	Run the ruff linter"
	@echo "  make format"
	@echo "  	Auto-format Python code"
	@echo "  make type_check"
	@echo "  	Run static type checking with pyright"
	@echo "  make clean"
	@echo "  	Remove autogenerated files like __py_cache__"
	@echo "  make changelog"
	@echo "  	Update the CHANGELOG"
	@echo "  make package"
	@echo "  	Build the package"
	@echo "  make publish"
	@echo "  	Publish the package to SIL's Pip Registry"
	@echo "  make help"
	@echo "  	Display usage information"